### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by Crescentz** [WenmuZhou/PSENet.pytorch#22]
Traceback (most recent call last):
  File "/home1/zy/YY/STR/PSENet.pytorch/cal_recall/rrc_evaluation_funcs.py", line 326, in main_evaluation
    evalData = evaluate_method_fn(p['g'], p['s'], evalParams)
  File "/home1/zy/YY/STR/PSENet.pytorch/cal_recall/script.py", line 136, in evaluate_method
    subm = rrc_evaluation_funcs.load_folder_file(submFilePath, evaluationParams['DET_SAMPLE_NAME_2_ID'], True)
  File "/home1/zy/YY/STR/PSENet.pytorch/cal_recall/rrc_evaluation_funcs.py", line 102, in load_folder_file
    raise Exception('ZIP entry not valid: %s' % name)
Exception: ZIP entry not valid: res_img_269.txt
Traceback (most recent call last):
  File "train.py", line 243, in <module>
    main()
  File "train.py", line 214, in main
    recall, precision, f1 = eval(model, os.path.join(config.output_dir, 'output'), config.testroot, device)
  File "train.py", line 145, in eval
    return result_dict['recall'], result_dict['precision'], result_dict['hmean']
TypeError: string indices must be integers

**Comment by WenmuZhou** [comment]
你可以debug看一下是哪里的错误，我这边没有遇到过

**Comment by Crescentz** [comment]
![image](https://user-images.githubusercontent.com/35165563/62441782-11962a80-b788-11e9-946b-8c132d40c49a.png)
问题指向了torch.optim.lr这个函数，应该是没有找到指定的学习率，
![image](https://user-images.githubusercontent.com/35165563/62441809-296dae80-b788-11e9-80f4-9f1582cb22a3.png)
注意到你在utlis里的lr_cheduler写了继承类，但是再debug时候还会跳转到torch里的optim，目前我还不知道该咋处理。。。

**Comment by Crescentz** [comment]
图片名称问题，找到原因了

**Comment by Arctanxy** [comment]
> 图片名称问题，找到原因了

你好，我也遇到了这个问题，想问下是哪里出了问题？

**Comment by Jialiang123** [comment]
> 
请问图片和gt文件到底应该咋命名呀，谢谢
