### ISSUE TITLE
为什么不能从现有的模型文件继续训练呢？是我的设置方式不对吗？

### ISSUE THREAD

**Issue by ztoString** [WenmuZhou/PSENet.pytorch#28]
config.py:
trainroot = './train'
testroot = './val'
output_dir = './results/v0_resnet50'
data_shape = 640

# train config
gpu_id = '0'
workers = 2
start_epoch = 0
epochs = 100

train_batch_size = 8

lr = 1e-4
end_lr = 1e-7
lr_gamma = 0.1
lr_decay_step = [200,400]
weight_decay = 5e-4
warm_up_epoch = 6
warm_up_lr = lr * lr_gamma

display_interval = 10
show_images_interval = 50
pretrained = True
restart_training = False
checkpoint = './PSENet_23_loss0.138575_r0.518665_p0.792499_f10.626987.pth'

# net config
backbone = 'resnet50'
Lambda = 0.7
n = 6
m = 0.5
OHEM_ratio = 3
scale = 1
# random seed
seed = 2

但是一直会提示错误：
Traceback (most recent call last):
  File "train.py", line 252, in <module>
    main()
  File "train.py", line 199, in main
    start_epoch = load_checkpoint(config.checkpoint, model, logger, device)
  File "/data3/resys/zoutong/ocr/PSENet.pytorch/utils/utils.py", line 74, in load_checkpoint
    model.load_state_dict(state['state_dict'])
  File "/data/resys/anaconda2/envs/ocr_pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for PSENet:
	Missing key(s) in state_dict: "backbone.conv1.weight", "backbone.bn1.weight", "backbone.bn1.bias", "backbone.bn1.running_mean", "backbone.bn1.running_var", "backbone.layer1.0.conv1.weight", "backbone.l.........

模型文件没有导对吗，不科学啊

**Comment by ztoString** [comment]
后来我想，可能是因为当时在训练的时候使用的双GPU，所以，这次我继续布置两个GPU来训练，但是又出现了新的错误：
2019-08-24 10:41:15 INFO      utils.py: models loaded from ./PSENet_23_loss0.138575_r0.518665_p0.792499_f10.626987.pth
Traceback (most recent call last):
  File "train.py", line 252, in <module>
    main()
  File "train.py", line 202, in main
    last_epoch=start_epoch)
  File "/data/resys/anaconda2/envs/ocr_pytorch/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 192, in __init__
    super(MultiStepLR, self).__init__(optimizer, last_epoch)
  File "/data/resys/anaconda2/envs/ocr_pytorch/lib/python3.6/site-packages/torch/optim/lr_scheduler.py", line 24, in __init__
    "in param_groups[{}] when resuming an optimizer".format(i))
KeyError: "param 'initial_lr' is not specified in param_groups[0] when resuming an optimizer"

**Comment by ztoString** [comment]
最后妥协的方案是：
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, config.lr_decay_step, gamma=config.lr_gamma,last_epoch=-1)
把last_epoch = start_epoch改成last_epoch = -1
虽然跑通了，但还是觉得有一丝的不科学

**Comment by WenmuZhou** [comment]
这里last_epoch是指lr_scheduler 不使用之前的状态，你在https://github.com/WenmuZhou/PSENet.pytorch/blob/master/train.py#L190 这一行把optimizer穿进去看看
