### ISSUE TITLE
訓練MTWI_2018數據集發生錯誤

### ISSUE THREAD

**Issue by f771216203** [WenmuZhou/PSENet.pytorch#68]
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    main()
  File "train.py", line 177, in main
    num_workers=int(config.workers))
  File "/home/yian/anaconda3/envs/psenet_pytorch/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 176, in __init__
    sampler = RandomSampler(dataset)
  File "/home/yian/anaconda3/envs/psenet_pytorch/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 66, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

我將訓練資料替換成MTWI_2018結果就報了以上錯誤，看起來label格式都是4個座標加注釋如下:
350.01,46.02,350.01,110.96,710.5,110.96,710.5,46.02,船用温度计
546.36,410.09,546.36,426.45,648.12,426.45,648.12,410.09,DaoGuan
491.65,327.25,491.65,356.91,502.38,356.91,502.38,327.25,###
178.71,324.7,178.71,356.4,490.11,356.4,490.11,324.7,13816752538
41.67,506.73,41.67,564.51,715.61,564.51,715.61,506.73,上海道冠五金有限公司
想請問除了config.py的trainroot以及train.py的img_path及gt_path更改以外我有哪裡漏改的嗎?還是座標需要是整數?

**Comment by f771216203** [comment]
找到dataset/data_utils.py裡的label_path好像也要做更改，另外想請問img與label檔案格式不是gt開頭的話該如何做更改才能成功訓練

**Comment by WenmuZhou** [comment]
更改datautil里dataset的代码

**Comment by f771216203** [comment]
![image](https://user-images.githubusercontent.com/46882260/78970041-00819280-7b3b-11ea-99a8-b2985f1da53d.png)

前面訓練都沒有報錯，直到第12個epoch出現了這個錯誤，想請問這樣是資料集哪裡出了問題?

**Comment by f771216203** [comment]
另外想請問為何要設計成框里的文本不能是### 或者*?目的不是文本檢測嗎後面的標籤應該不影響吧

**Comment by WenmuZhou** [comment]
图片你的错误是有一个文本的长度被计算为0了，检查下标注
###是因为有些公开数据集的模糊样本被标注为这样的

**Comment by zqnnn** [comment]
> ![image](https://user-images.githubusercontent.com/46882260/78970041-00819280-7b3b-11ea-99a8-b2985f1da53d.png)
> 
> 前面訓練都沒有報錯，直到第12個epoch出現了這個錯誤，想請問這樣是資料集哪裡出了問題?

请问你解决这个问题了吗，我也遇到了

**Comment by NextGuido** [comment]
> > ![image](https://user-images.githubusercontent.com/46882260/78970041-00819280-7b3b-11ea-99a8-b2985f1da53d.png)
> > 前面訓練都沒有報錯，直到第12個epoch出現了這個錯誤，想請問這樣是資料集哪裡出了問題?
> 
> 请问你解决这个问题了吗，我也遇到了

@zqnnn 说一下我的解决方法，将下方的代码注释掉重新运行即可。不知道对不对，但是我的数据重新运行不会出现这个问题了：
https://github.com/WenmuZhou/PSENet.pytorch/blob/278cc301a47ee342688a4c0ee5119b53a5df64a7/dataset/data_utils.py#L53

**Comment by zqnnn** [comment]
> > > ![image](https://user-images.githubusercontent.com/46882260/78970041-00819280-7b3b-11ea-99a8-b2985f1da53d.png)
> > > 前面訓練都沒有報錯，直到第12個epoch出現了這個錯誤，想請問這樣是資料集哪裡出了問題?
> > 
> > 
> > 请问你解决这个问题了吗，我也遇到了
> 
> @zqnnn 说一下我的解决方法，将下方的代码注释掉重新运行即可。不知道对不对，但是我的数据重新运行不会出现这个问题了：
> 
> https://github.com/WenmuZhou/PSENet.pytorch/blob/278cc301a47ee342688a4c0ee5119b53a5df64a7/dataset/data_utils.py#L53

请问你是按照icdar15的数据格式重新调整了MTWI数据嘛？我是指文本框方向还有整数

**Comment by zqnnn** [comment]
@NextGuido 
请问你是按照icdar15的数据格式重新调整了MTWI数据嘛？我是指文本框方向还有整数

**Comment by NextGuido** [comment]
> @NextGuido
> 请问你是按照icdar15的数据格式重新调整了MTWI数据嘛？我是指文本框方向还有整数

对的
