### ISSUE TITLE
Problems during training

### ISSUE THREAD

**Issue by Waynepoo** [WenmuZhou/PSENet.pytorch#77]
Traceback (most recent call last):
  File "train.py", line 263, in <module>
    main()
  File "train.py", line 217, in main
    recall, precision, f1 = eval(model, os.path.join(config.output_dir, 'output'), config.testroot, device)
  File "train.py", line 132, in eval
    h, w = img.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
test models:  85%|##########################################################################################################6                  | 29/34 [02:08<00:22,  4.44s/it]

![image](https://user-images.githubusercontent.com/41176549/81542397-2a7edc80-93a7-11ea-95f4-a2d2b11a9546.png)

**Comment by Debugerss** [comment]
看一下图片读进去没，如果你是在linux系统下，你最好进文件夹ls一下，看看是否有不是图片的文件

**Comment by Waynepoo** [comment]
> 看一下图片读进去没，如果你是在linux系统下，你最好进文件夹ls一下，看看是否有不是图片的文件

谢谢，文件夹中多了一个自动生成的文件，删除解决了，但是在eval函数中（141-150行），boxes_list返回时空，导致报下面的错误：

Traceback (most recent call last):
  File "/mnt/data/ocr/psenet/PSENet.pytorch-master/cal_recall/rrc_evaluation_funcs.py", line 326, in main_evaluation
    evalData = evaluate_method_fn(p['g'], p['s'], evalParams)
  File "/mnt/data/ocr/psenet/PSENet.pytorch-master/cal_recall/script.py", line 136, in evaluate_method
    subm = rrc_evaluation_funcs.load_folder_file(submFilePath, evaluationParams['DET_SAMPLE_NAME_2_ID'], True)
  File "/mnt/data/ocr/psenet/PSENet.pytorch-master/cal_recall/rrc_evaluation_funcs.py", line 102, in load_folder_file
    raise Exception('ZIP entry not valid: %s' % name)
Exception: ZIP entry not valid: res_F011912250373_002.txt
Traceback (most recent call last):
  File "train.py", line 265, in <module>
    main()
  File "train.py", line 219, in main
    recall, precision, f1 = eval(model, os.path.join(config.output_dir, 'output'), config.testroot, device)
  File "train.py", line 151, in eval
    return result_dict['recall'], result_dict['precision'], result_dict['hmean']
TypeError: string indices must be integers



是我迭代次数太少，导致没有检测到结果吗？   大神帮忙看看这是什么问题，非常感谢

**Comment by 15926273249** [comment]
请问数据集的格式是怎么样的，可以发一份完整的数据集吗

**Comment by hwqgsoso** [comment]
你好,请问解决了吗

**Comment by hwqgsoso** [comment]
TypeError: string indices must be integers

**Comment by xunlonghuang** [comment]
> > 看一下图片读进去没，如果你是在linux系统下，你最好进文件夹ls一下，看看是否有不是图片的文件
> 
> 谢谢，文件夹中多了一个自动生成的文件，删除解决了，但是在eval函数中（141-150行），boxes_list返回时空，导致报下面的错误：
> 
> Traceback (most recent call last):
> File "/mnt/data/ocr/psenet/PSENet.pytorch-master/cal_recall/rrc_evaluation_funcs.py", line 326, in main_evaluation
> evalData = evaluate_method_fn(p['g'], p['s'], evalParams)
> File "/mnt/data/ocr/psenet/PSENet.pytorch-master/cal_recall/script.py", line 136, in evaluate_method
> subm = rrc_evaluation_funcs.load_folder_file(submFilePath, evaluationParams['DET_SAMPLE_NAME_2_ID'], True)
> File "/mnt/data/ocr/psenet/PSENet.pytorch-master/cal_recall/rrc_evaluation_funcs.py", line 102, in load_folder_file
> raise Exception('ZIP entry not valid: %s' % name)
> Exception: ZIP entry not valid: res_F011912250373_002.txt
> Traceback (most recent call last):
> File "train.py", line 265, in
> main()
> File "train.py", line 219, in main
> recall, precision, f1 = eval(model, os.path.join(config.output_dir, 'output'), config.testroot, device)
> File "train.py", line 151, in eval
> return result_dict['recall'], result_dict['precision'], result_dict['hmean']
> TypeError: string indices must be integers
> 
> 是我迭代次数太少，导致没有检测到结果吗？ 大神帮忙看看这是什么问题，非常感谢

您好，请问您这个问题是否解决了呢？

**Comment by xunlonghuang** [comment]
> > 看一下图片读进去没，如果你是在linux系统下，你最好进文件夹ls一下，看看是否有不是图片的文件
> 
> 谢谢，文件夹中多了一个自动生成的文件，删除解决了，但是在eval函数中（141-150行），boxes_list返回时空，导致报下面的错误：
> 
> Traceback (most recent call last):
> File "/mnt/data/ocr/psenet/PSENet.pytorch-master/cal_recall/rrc_evaluation_funcs.py", line 326, in main_evaluation
> evalData = evaluate_method_fn(p['g'], p['s'], evalParams)
> File "/mnt/data/ocr/psenet/PSENet.pytorch-master/cal_recall/script.py", line 136, in evaluate_method
> subm = rrc_evaluation_funcs.load_folder_file(submFilePath, evaluationParams['DET_SAMPLE_NAME_2_ID'], True)
> File "/mnt/data/ocr/psenet/PSENet.pytorch-master/cal_recall/rrc_evaluation_funcs.py", line 102, in load_folder_file
> raise Exception('ZIP entry not valid: %s' % name)
> Exception: ZIP entry not valid: res_F011912250373_002.txt
> Traceback (most recent call last):
> File "train.py", line 265, in
> main()
> File "train.py", line 219, in main
> recall, precision, f1 = eval(model, os.path.join(config.output_dir, 'output'), config.testroot, device)
> File "train.py", line 151, in eval
> return result_dict['recall'], result_dict['precision'], result_dict['hmean']
> TypeError: string indices must be integers
> 
> 是我迭代次数太少，导致没有检测到结果吗？ 大神帮忙看看这是什么问题，非常感谢

这个问题的原因是因为数据集格式没有按照Readme里面说的格式而产生的，可以修改数据集格式，或者修改script.py里default_evaluation_params里面的匹配规则。

**Comment by zzzzjx** [comment]
请问如何修改训练任意点训练呢

**Comment by aojue1109** [comment]
> Exception: ZIP entry not valid

这个确实是script.py里面的正则表达式问题，建议在里面写一个main函数，跑一下自己的数据集，看看是否都能够通过验证；比如我的修改为：
ef default_evaluation_params():
    """
    default_evaluation_params: Default parameters to use for the validation and evaluation.
    """
    return {
        'IOU_CONSTRAINT': 0.5,
        'AREA_PRECISION_CONSTRAINT': 0.5,
        # 'GT_SAMPLE_NAME_2_ID': 'gt_img_([0-9]+).txt',
        'GT_SAMPLE_NAME_2_ID': 'gt_img_(.*).txt',
        # 'DET_SAMPLE_NAME_2_ID': 'res_img_([0-9]+).txt',
        'DET_SAMPLE_NAME_2_ID': 'res_img_(.*).txt',
        'LTRB': False,  # LTRB:2points(left,top,right,bottom) or 4 points(x1,y1,x2,y2,x3,y3,x4,y4)
        'CRLF': False,  # Lines are delimited by Windows CRLF format
        'CONFIDENCES': False,  # Detections must include confidence value. AP will be calculated
        'PER_SAMPLE_RESULTS': True  # Generate per sample results and produce data for visualization
    }
图片的命名规则将不局限于数字，自己可根据实际修改
